export const WEATHER_FETCH_SUCCESS = 'WEATHER_FETCH_SUCCESS';
export const WEATHER_FETCH_START = 'WEATHER_FETCH_START';
export const WEATHER_FETCH_ERROR = 'WEATHER_FETCH_ERROR';

export const WEATHER_REMOVE_START = 'WEATHER_REMOVE_START';
